FROM selenium/node-firefox

USER root

# Install nodejs 12
RUN curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
RUN sudo apt-get install -y nodejs

# Build application
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . ./

USER seluser

ENV SELENIUM_BROWSER=firefox

ENTRYPOINT [ "npm", "test" ]
